#!/usr/bin/env bash

##  qqX component to be located in folder 'qqX.main'

##  Copyright (c)  Alex Genovese   https://github.com/qqxproject
#   SMALL CODE SNIPPETS eg the function printColor MAY BE USED
#   PERMISSIVELY in projects as MIT or similar, providing CLEAR ATTRIBUTIONS are shown.
# 	Otherwise:
#   Licence  GPL3   https://www.gnu.org/licenses
##  qqX - quickemu quickget X terminal project

## ShellCheck global disables:
# https://www.shellcheck.net/wiki/SC2242 as it clashes with use of exit traps used to keep mouse click scripts open
# And SC1090,SC1091,SC2024, SC2154 for necessity of dynamic file sourcing

#  shellcheck disable=SC2242,SC1090,SC1091,SC2034,SC2154


custom_conf_notes () {

  printColor "\n\n  qqX .conf reminders:"

  printf "

    #!/usr/bin/qqX --vm                (for qqX direct start)

    Custom_SDL_ScreenPercent=\"xx\"      (integer from 25 to 99)
    Custom_SDL_ScreenSize=\"WxH\"        (qe 4.95+ eg 2560x1440)
    HeadlessDisplay=\"true\"

    SecondDrive=\"My_Folder/My_VM/disk2.qcow2\"
    SharedDrive_Conf=\"no-shared\"
    MacLegacyDrive=\"true\"

    Other:
    disk_size=\"xxG\"   (integer, used once, for first build)
    cpu_cores=\"x\"     (even integer)
    ram=\"xG\"          (integer)
    keyboard=           'usb' (default), 'ps2', 'virtio'
    keyboard_layout=    'en-us' (default)
    mouse=              'tablet' (default), 'ps2', 'usb', 'virtio'
    network=            'bridge' >> -nic bridge,br=bridge,model=virtio-net-pci

    boot=\"legacy\"     (use bios, not UEFI) default: =\"efi\"

    Windows:
    tpm=\"on\"          secureboot=\"off\"
    gl=\"off\"          (scaleable SDL, easier restarts) (?)

    Early 2025 Insider betas are now requesting Secure Boot.
    Tests are showing seemingly successful outcomes when set to \"on\"

    Difficult booting:
    boot=\"legacy\"  &  gl=\"off\"  may help ...

    highlight then shift-ctrl-c  to copy ...
  \n"
}

function check_screen_percentage_and_output {

  SDL_ScreenSize_Error=
  SDL_ScreenSize_Cmd=
  HeadlessCmd=

  #  Function 'refresh_conf_vars_and_values' should clear all existing .conf vars before sourcing a new conf file
  #  Note that 'gl' is a quickemu internal variable which quickemu defaults to "on"
  #  From quickemu 4.8 onwards, the value " --screenpct xx"  may be used on SDL, where xx is a value from 25 to 99  & Linux VM's only.
  #  But check the source to see if the case option exists, don't rely on the version number as formats change or could be a custom version.

  if [[ $gl == "off" || $gl == "on" ]]; then  qqX_GL_Mode="$gl"
  else
    if [[ $SetGL_DefaultAsOff ]]; then qqX_GL_Mode="off" ; else qqX_GL_Mode="on" ; fi
  fi

  SDL_ScreenPercent=

  [[ $Custom_SDL_ScreenPercent ]] && SDL_ScreenPercent="$Custom_SDL_ScreenPercent"
  [[ $Default_SDL_ScreenPercent ]] && [[ ! $SDL_ScreenPercent ]] && SDL_ScreenPercent="$Default_SDL_ScreenPercent"

  if [[ $SDL_ScreenPercent ]]; then

    SDL_ScreenPercent="$(tr -cd "[:digit:]" <<< "$SDL_ScreenPercent")"
    [[ SDL_ScreenPercent -lt 25 ]] && SDL_ScreenPercent="25"
    [[ SDL_ScreenPercent -gt 97 ]] && SDL_ScreenPercent="97"

    if  grep -q -s -e 'screenpct' "/tmp/qmod-case-temp" ; then
      SDL_ScreenSize_Cmd=" --screenpct  $SDL_ScreenPercent"
    else
      if [[ ! $QE_495_Script ]] && [[ ! $QE_496_Script ]]; then
        printColor "\n\n  WARNING:  SDL_ScreenPercent needs quickemu 4.8+ \n\n "
        SDL_ScreenSize_Error="> not possible with this qe-version"
      fi
    fi

  fi

  xRes=
  yRes=
  Mon_xRes=
  Mon_yRes=
  SDL_ScreenSize=
  MacScreenRes=
  SDL_ScreenSize_Cmd97=

  if [[ $QE_495_Script || $QE_496_Script ]] && [[ $XDG_SESSION_TYPE == "x11" || $XDG_SESSION_TYPE == "wayland" ]]; then

    if [[ $PhysicalMonitor ]]; then
      Mon_xRes="$(cut -d 'x' -f 1 <<< "$PhysicalMonitor")"
      Mon_yRes="$(cut -d 'x' -f 2 <<< "$PhysicalMonitor")"
    else
      Mon_xRes=$(xrandr --listmonitors | grep -v Monitors | cut -d' ' -f4 | cut -d'/' -f1 | head -n1)
      Mon_yRes=$(xrandr --listmonitors | grep -v Monitors | cut -d' ' -f4 | cut -d'/' -f2 | cut -d'x' -f2 | head -n1)
    fi

    Mon_xRes="$(tr -cd "[:digit:]" <<< "$Mon_xRes")"
    Mon_yRes="$(tr -cd "[:digit:]" <<< "$Mon_yRes")"

    if [[ ! $Mon_xRes || ! $Mon_yRes ]]; then
      if [[ $PhysicalMonitor ]]; then printColor "\n\n  ERROR: check monitor size in general settings \n\n "
      else printColor "\n\n  ERROR: xrandr detection > set manually in general settings \n\n "
      fi
      SDL_ScreenSize_Error="> monitor size error"
    fi

    [[ $Custom_SDL_ScreenSize ]] && SDL_ScreenSize="$Custom_SDL_ScreenSize"
    [[ $MacScreenRes ]] && SDL_ScreenSize="$MacScreenRes"
    [[ $Default_SDL_ScreenSize ]] && [[ ! $SDL_ScreenSize ]] && SDL_ScreenSize="$Default_SDL_ScreenSize"

    # MacOS REVIEW  # ? 1360 x 768  ? 1920 x 1080 (max ovmf)  ? 1280 x 720  (max default qxl)
    # The newer variable SDL_ScreenSize is functionally identical to MacScreenRes
    # but MacScreenRes has been left in place to emphasise that size options are more limited if used with Mac.
    # Sonoma default is 2560 x 1440 low res. In other words 1280 x 720 at x2 Hi-DPI res.
    # Mac seems to be able to use 1280 and then takes control of the outcome itself, once set up.
    # Unless it's Sequoia where it needs to be specified in the conf file:
    if [[ $guest_os == "macos" ]]; then
      if [[ $MacScreenRes ]] && [[ ! $Custom_SDL_ScreenSize ]]; then
        SDL_ScreenSize="$MacScreenRes"
      else xRes=1280 && yRes=720
      fi
    fi

    if [[ $SDL_ScreenSize ]]; then

      xRes="$(cut -d 'x' -f 1 <<< "$SDL_ScreenSize")"
      yRes="$(cut -d 'x' -f 2 <<< "$SDL_ScreenSize")"
      xRes="$(tr -cd "[:digit:]" <<< "$xRes")"
      yRes="$(tr -cd "[:digit:]" <<< "$yRes")"

      if [[ ! $xRes || ! $yRes ]]; then
        printColor "\n\n  ERROR: check specified sizes in settings \n\n "
        SDL_ScreenSize_Error="> display size error"
      fi

    elif [[ $SDL_ScreenPercent ]]; then

      xRes="$(bc <<< "scale=0; $Mon_xRes*$SDL_ScreenPercent/100")"
      yRes="$(bc <<< "scale=0; $Mon_yRes*$SDL_ScreenPercent/100")"
      SDL_ScreenSize_Cmd=" --width $xRes --height $yRes"
      SDL_ScreenSize="${xRes}x${yRes}"

    else
      xRes=1152 && yRes=648
    fi

    SDL_ScreenSize_Cmd=" --width $xRes --height $yRes"

    # Windows and Mac REVIEW

    if [[ $guest_os == "windows" || $guest_os == "macos" ]]; then
      SDL_ScreenSize_Cmd97=
    else
      xRes97="$(bc <<< "scale=0; $Mon_xRes*97/100")"
      yRes97="$(bc <<< "scale=0; $Mon_yRes*97/100")"
      SDL_ScreenSize_Cmd97=" --width $xRes97 --height $yRes97"
    fi

  fi

  [[ $HeadlessDisplay != "true" ]] && HeadlessDisplay=
  [[ $HeadlessDisplay ]] && HeadlessCmd=" --display  none"

}

function set_drive_paths {

  #  For a SECOND/SHARED DRIVE (idea from @gnudoc on the quickemu Discord channel)  do "qemu-img create -f qcow2 disk2.qcow2 40G"  or as required
  #  Set  ExtraArgs=" -device virtio-blk-pci,drive=SharedDrive -drive id=SharedDrive,if=none,format=qcow2,file=/vm_folder/disk2.qcow2"
  #  Edit path & boot a VM.  Use 'Disks'  Gparted or similar to find, format and mount.
  #  The function needs to be run everytime a different VM is selected to allow for individual VM settings or requirements.

  #  Older versions of MacOS require a non pci set up. See quickemu script "Qemu optimisations based on the macOS release"
  #  Any OS older than and including 10.13 Mojave 2018 should have a flag in the .conf file > MacLegacyDrive="true"
  #  See https://en.wikipedia.org/wiki/MacOS_version_history


  #  SECOND DRIVE and .conf file
  #  Drive path to be individually set in the .conf file on a per VM basis.

  #  NOTE: From qqX ver 1.5 onwards, this function now gets called by 'refresh_conf_vars_and_values'
  #  which will have already sourced the .conf file and its variables

  if [[ $MacLegacyDrive == "true" ]]; then  BusType="ide-hd,bus=ahci.2"

  else BusType="virtio-blk-pci"; fi

  #  SECOND DRIVE
  #  Drive path to be individually set in the .conf file on a per VM basis.

  if [[ -e "$SecondDrive" ]]; then

    SecondDriveArgs=" -device ${BusType},drive=SecondDrive -drive id=SecondDrive,if=none,format=qcow2,file=$SecondDrive"

  elif [[ $SecondDrive ]]; then

    # whilst the conf entry exists the above test didn't find it
    DriveLocationError="ERROR SecondDrive NOT found (.conf file)"

  fi

  #  SHARED DRIVE
  #  This drive should be availble to all VMs and act as a shared resource.  See main settings.

  if [[ $(grep -s 'SharedDrive=' "$qqX_SettingsFile" | grep -v '#' | grep -c 'SharedDrive') == 1 ]]; then
      eval "$(grep -s 'SharedDrive=' "$qqX_SettingsFile" | grep -v '#' )"
  fi

  if [[ $SharedDrive ]]; then

    # if not toggled from the main menu, then read the .conf file
    [[ ! $SharedDrive_Mount ]] && eval "$(grep -s SharedDrive_Conf "$VM_Conf_File" | grep -v '#')"

    if [[ $MacLegacyDrive ]] || [[ $SharedDrive_Conf ==  "no-shared" ]]; then
      SharedDriveArgs=
    elif [[ -e "$SharedDrive" ]]; then
      [[ ! $BusType ]] && BusType="virtio-blk-pci"
      SharedDriveArgs=" -device ${BusType},drive=SharedDrive -drive id=SharedDrive,if=none,format=qcow2,file=$SharedDrive"
    elif [[ $SharedDrive ]]; then
      DriveLocationError="ERROR SharedDrive NOT found (main settings)"
    fi

  fi

}


#  MAIN DRIVE & BOOT
# 'refresh_conf_vars_and_values' from qqX ver 1.5 will source the quickemu .conf file
#  everytime a different VM is selected or the .conf file is reconfigured
#  NB Quickemu uses vars:  'disk_img' for  main .qcow2  &  either a bootable 'iso=' or 'img=' for first time or Live boots
#  Error handling for this function is also actioned by 'show_main_menu_header'

function read_main_drive_and_img_iso_conf_vars {

  MainDrive=
  IsoImg=

  if [[ $Trace_InputVars ]]; then
    echo "QE Conf Var 'disk_img': $disk_img"  ; echo
    echo "QE Conf Var 'img': $img"  ; echo
    echo "QE Conf Var 'iso': $iso"  ; echo
    sleep "$Trace_InputVars"
  fi

  if [[ ! $IgnoreConfigErrors ]]; then
    [[ $disk_img ]] && [[ ! -d  "$(dirname "$disk_img")" ]] && function_conf_error  folder  "disk_img:  $(dirname "$disk_img")"
    [[ $img ]] && [[ ! -d  "$(dirname "$img")" ]] && function_conf_error  folder  "img:  $(dirname "$img")"
    [[ $iso ]] && [[ ! -d  "$(dirname "$iso")" ]] && function_conf_error  folder  "iso:  $(dirname "$iso")"
  fi

  [[ -e "$disk_img" ]] && MainDrive="$disk_img"
  [[ -e "$img" ]] && IsoImg="$img"
  [[ -e "$iso" ]] && IsoImg="$iso"

}

check_conf_file_for_typos () {
  # To be run before sourcing-in the config settings. Check for common mistakes.
  local CheckFile= ; CheckFile="$1" ; local ConfChkArr=() ; local Line= ; ConfTypo=
  mapfile -t ConfChkArr < "$CheckFile"
  for Line in "${ConfChkArr[@]}" ; do
    if awk '{print $1}' <<< "$Line" | grep -qs -e ^'#' ; then true
    elif grep -q -e ' =' -e '= ' <<< "$Line" ; then ConfTypo="Equals Spacing:  $Line" ; break
    fi
  done
  if [[ $ConfTypo ]]; then function_conf_error "ConfTypo" "$ConfTypo"
  fi
}

function_conf_error () {
  ErrorMenuSelect= ; NewSetupFlag=
  # clear any accidental initial double pressing of the enter key occuring while experiencing the error
  read -r -t 0.1 ; read -r -t 0.1 ; read -r -t 0.1 ; read -r -t 0.1 ; read -r -t 0.1

  if [[ $NewFileTuneUp_JustDone ]]; then NewFileTuneUp_JustDone= ; return ; fi

  printColor "\n\n  qqX Settings, VM folder & conf file(s)"
  if [[ $1 == "No VMs" ]] ; then
    printColor "\n\n  No VMs - Probably time to welcome you to qqX and invite you to get some distros."
    printf "\n\n  The settings file and locations can usually be left till later ..."
  elif [[ $1 ]] ; then
    printf "\n\n  Check %s settings, possibly LOCATION and/or CONTENT ... "  "$1"
  else
    printf "\n\n  Check the settings and re-run this script ... "
  fi

 [[ $Loop_Diagnostics ]] && echo
  main_loop_diagnostics

  printf "\n\n  General Settings file:  %s \n\n" "$qqX_SettingsFile"

  if [[ "$1" == *'COMMAND'* ]]; then
    printColor "\n\n  [q] to quit "
    printf "  [enter] to view/edit settings file \n\n"

  elif [[ $1 == "new" ]]; then
    printColor "\n  Starting NEW VIRTUAL MACHINE: \n\n"
    cat "$VM_Conf_File"
    NewSetupFlag=1 ; IgnoreFolderCheck=1 ; SelectArrayError=
    printf "\n\n\n  [enter]  edit the .conf file   [tune] run the config tune-up wizard "
    printColor "\n\n  [c] continue  (with current settings) looks okay "
    printf "\\n\n  [d] delete   [e] to edit qqX general settings   [q] to quit \n\n"

  elif [[ $1 == "ConfTypo" ]]; then
    printColor "\n  Typo errors in the Config file: \n\n"
    cat "$VM_Conf_File"
    printColor "\n\n  %s" "$2"
    NewSetupFlag= ; IgnoreFolderCheck= ; SelectArrayError=
    printColor "\n\n\n  [enter]  edit the .conf file   [tune] run the config tune-up wizard "
    printf "\n\n  [c] continue  (with current settings)  > ignore "
    printf "\\n\n  [q] to quit \n\n"

  elif [[ $1 == "folder" ]] ; then
    FolderConfigFlag=1
    printf "\n  Folder config ERROR:"
    [[ $2 ]] && printf "  '%s'"  "$2"
    printf "\n\n  Check the folder path with the file manager. Check for spellings. Check upper/lower case."
    printf "\n\n  Esp. check for spaces that may have been true-typed into semi-invisibility ... "
    printColor "\n\n\n  [enter] to edit the .conf file   [e]  edit qqX general settings "
    printf "\n\n  [c] ignore and continue"
    [[ $FileManager ]] && printf "   [f] open group folder in file-manager"
    printf "   [q] to quit \n\n"

  elif [[ $1 == "qqX_SettingsFile" ]] ; then
    printf "\n  INTERNAL ERROR: "
    printColor "\n\n\n  Settings file not found: %s"  "$qqX_SettingsFile"
    printf "\n\n  [c] ignore and continue   [q] to quit \n\n"

  else
    # includes "$1" = ".conf file"
    printColor "\n\n  [Enter] to edit qqX general settings"
    [[ "$1" == *'No VMs'* ]] && printColor "  [gt] quickget a new distro "
    printf "  [c] ignore and continue "
    printf "  [q] to quit \n\n"

  fi

  read -rp "  >  "   ErrorMenuSelect


  if [[ $ErrorMenuSelect == "q" ]]; then  printf "\n\n"; command exit

  elif [[ $ErrorMenuSelect == "f" ]]; then (nohup &> /dev/null  "$FileManager"  "$VM_Conf_Dir" & ) || file_manager_not_found_message

  elif [[ $ErrorMenuSelect == "tune" ]]; then  function_config_tune_up  "$VM_Conf_Dir/$VM_Conf_File"

  elif [[ $ErrorMenuSelect == "c" || $ErrorMenuSelect == "d" || $ErrorMenuSelect == "e" || $ErrorMenuSelect == "gt" ]]; then

    IgnoreFolderCheck=1 ; IgnoreConfigErrors=1

    if [[ $ErrorMenuSelect == "c" ]]; then  SelectArrayError= ; IgnoreSecondCheckNew=1 ; FolderConfigFlag= ; return 0

    elif [[ $ErrorMenuSelect == "d" ]]; then  SelectArrayError= ; IgnoreSecondCheckNew=1 ; MainMenuChoicePreset="del" ; return 0

    elif [[ $ErrorMenuSelect == "e" ]]; then

      if [[ $NewSetupFlag || $FolderConfigFlag ]]; then VM_InstanceName= ; qqX_edit_settings ; else qqX_edit_settings  "conf" ; fi

    elif [[ $ErrorMenuSelect == "gt" ]]; then

      VM_Selection=
      VM_InstanceName= ; VM_Conf_Dir= ; VM_Conf_File=
      cd "$Default_VM_Folder" || DefaultFolderError=1
      Current_VM_Folder="$Default_VM_Folder"
      function_quick_get_wrap
      return 0

    fi

  else

    if [[ $NewSetupFlag || $FolderConfigFlag || $ConfTypo ]]; then
      NewSetupFlag= ; FolderConfigFlag= ; ConfTypo=
      qqX_edit_settings  "conf"
    else  qqX_edit_settings
    fi

  fi

}

qqX_edit_settings() {

  if [[ $TextEditor ]] && [[ ! $(type -p "$TextEditor") ]]; then texteditor_not_found_message
  else
    # Run the editor:
    if [[ $1 == "conf" ]]; then

      printf "\n\n"
      cat "$VM_Conf_Dir/$VM_Conf_File"
      printf "\n\n"

      while true ; do
        printColor "\n  [enter] to edit   [n] conf notes  [d] conf defaults list   [t] config tune-up wizard   [b] go back"
        printf "\n\n"
        read -rp "  >  "   ConfEdit_Select
        if [[ $ConfEdit_Select == "n" ]] ; then  custom_conf_notes
        elif [[ $ConfEdit_Select == "d" ]] ; then
          printColor "\n\n  Standard Quickemu hard-coded defaults: \n"
          grep -s -B 200 ACCESS "/tmp/qmod-qe-all-vars-temp" | grep -v -e ACCESS -e MAIN -e Lowercase
        elif [[ $ConfEdit_Select == "t" ]] ; then   function_config_tune_up "$VM_Conf_Dir/$VM_Conf_File" ; break
        elif [[ $ConfEdit_Select == "b" ]] ; then  break
        else
          cp "$VM_Conf_File" "$VM_InstanceName/${VM_Conf_File}.edit.old.txt"
          (nohup &> /dev/null  "$TextEditor" "$VM_Conf_Dir/$VM_Conf_File" & ) || texteditor_not_found_message
          custom_conf_notes
          printColor "\n  [enter] to return, or when editing has been completed, to refresh \n\n"
          read -rp "  >  "
          ConfSettingsAdjusted=1
          refresh_conf_vars_and_values
          break
        fi
      done

    elif [[ $1 == "custom" ]]; then

      (nohup &> /dev/null   "$TextEditor" "$QemuArgsCustomFile"  & )  || texteditor_not_found_message

    elif [[ $1 == "tune-up" ]]; then

      (nohup &> /dev/null   "$TextEditor" "$TuneUpTargetDraft" )  || texteditor_not_found_message
      ConfSettingsAdjusted=1
      refresh_conf_vars_and_values

    else

      (nohup &> /dev/null   "$TextEditor" "$qqX_SettingsFile" )  || texteditor_not_found_message
      if [[ $DefaultFolderError ]]; then
        printColor "\n\n  A qqX restart is required ...."
        printf "\n\n  [enter] to close \n\n"
        read -rp "  >  "
        exit directly
      else
        sleep 1
        printColor "\n  refreshing sources and arrays .... \n\n"
        SettingsFileAdjusted=1
        refresh_sources_and_load_VM_arrays
      fi

    fi

    # Note, app opening commands can throw a complaint if 'xapps' has not not been installed.
    # https://askubuntu.com/questions/1396739/failed-to-load-module-xapp-gtk3-module

    # NB  don't set to run the editor in the background, as the web browser does, as qqX needs to take the new settings

  fi

}

function refresh_logfile_locations {

    QemuArgsFile="$VM_Conf_Dir/$VM_InstanceName/Qemu_args_List.txt"
    QemuArgsShortFile="$VM_Conf_Dir/$VM_InstanceName/Qemu_ShortArgs_List.txt"
    QemuArgsCustomFile="$VM_Conf_Dir/$VM_InstanceName/Qemu_ShortArgs_Custom.txt"
    QemuVirtHardwareRecord="$VM_Conf_Dir/$VM_InstanceName/QemuVirtHardwareRecord.txt"

    # Qemu_IMG log > eg. for disk repair functions
    Qemu_IMG_ErrorLog="$VM_InstanceName/${VM_InstanceName}.qemu.IMG.error.log"
    if [[ $(cat "$Qemu_IMG_ErrorLog" 2>/dev/null) ]]; then printf "\n\n" ; cat "$Qemu_IMG_ErrorLog" ; fi

    # Qemu SYSTEM log  # keep log, only clear if booting up afresh (in menu actions)
    if [[ -d  "$VM_Conf_Dir/$VM_InstanceName" ]]; then
      QemuErrorLog="$VM_Conf_Dir/$VM_InstanceName/${VM_InstanceName}.qemu.error.log"
      [[ ! -e "$QemuErrorLog" ]] && printf "" >  "$QemuErrorLog"
    fi
}

function alert_on_new {
    # test for 'new' - will have have an iso/img but not a main drive, yet (but also double check if 'just done')
    if [[ -e "$IsoImg" &&  ! -e "$MainDrive" ]] && [[ ! $NewFileTuneUp_JustDone ]]; then
      if [[ $IgnoreSecondCheckNew || $VM_Renamed ]]; then IgnoreSecondCheckNew= ; else  function_conf_error "new" ; fi
    fi
}

function refresh_conf_vars_and_values {

  # All existing .CONF VARS MUST BE CLEARED before sourcing a new conf file
  # otherwise any items specified in any previous config, but not in the new one, will remain.
  # Needed from qqX ver 1.5 onwards

  # A blank clearance will have been created at first session start.

  if [[ -e $VM_Conf_File ]]; then

    # this code only runs if a conf file has been specified, otherwise does nothing ...
    # but make sure that the calling code has put us in the right place, if a conf file is there
    if [[ "$(pwd)" != "$VM_Conf_Dir" ]]; then function_conf_error  "Conf Refresh:  WRONG FOLDER ," ; fi

    # And make sure that $VM_Conf_File has not somehow inherited the whole path
    VM_Conf_File="$(basename "$VM_Conf_File")"
    if [[ ! -e "$VM_Conf_Dir/$VM_Conf_File" ]]; then function_conf_error  "Conf Refresh:  WRONG FOLDER/FILE ," ; fi

    source "$ConfClearanceLog"
    SecondDrive=
    SharedDrive=
    DriveLocationError=
    SharedDrive_Conf=
    SecondDriveArgs=
    SharedDriveArgs=
    SharedDrive_Mount=
    MacLegacyDrive=
    QemuError_VM_Filter=()
    Custom_SDL_ScreenSize=
    Custom_SDL_ScreenPercent=
    ACCESS=
    QemuArgsCustomFile=
    QemuErrorLog=
    #reload_boot_style_defaults  # REVIEW
    # left off as if active then utils menu bm function reverts to defaults after booting once ...
    # at ver 1.12.01 has been placed into qqX main loop so switching vm is clean

    [[ $Loop_Diagnostics ]] && printf "\n\n Conf refresh 1:" &&  main_loop_diagnostics

    # clear & re-populate the ConfClearanceLog with current fields, for the next occasion

    printf "#%s/%s" "$VM_Conf_Dir" "$VM_InstanceName"  > "$ConfClearanceLog"
    mapfile -t ConfClearance_Arr < "$VM_Conf_Dir/$VM_Conf_File"

    for Line in "${ConfClearance_Arr[@]}"; do
      if [[ $Line ]] && [[ "$Line" == *'='* ]]; then
        if [[ "$Line" == *'QemuError_VM_Filter'* ]]; then Line='QemuError_VM_Filter=()'
        else
          Line="$(cut -d'=' -f1 <<< "$Line")"
          Line="$Line""="
          [[ "$Line" == *'#'* ]] && Line="${Line/'#'/}"

        fi
        printf "\n\n%s" "$Line" >> "$ConfClearanceLog"
        # Note that commented out lines need including, in case the comment marker gets removed
      fi

    done

    source "$ConfClearanceLog"
    check_conf_file_for_typos "$VM_Conf_Dir/$VM_Conf_File"
    source "$VM_Conf_Dir/$VM_Conf_File"

    [[ $Loop_Diagnostics ]] && printf "\n\n Conf refresh 2:" &&  main_loop_diagnostics
    # check any menu values that are based on the file .conf
    check_screen_percentage_and_output
    read_main_drive_and_img_iso_conf_vars
    set_drive_paths
    check_disk_is_okay

    refresh_logfile_locations

    [[ $Loop_Diagnostics ]] && printf "\n\n Conf refresh 3:" &&  main_loop_diagnostics

  fi

}

