#!/usr/bin/env bash

##  qqX component to be located in folder 'qqX.main'

##  Copyright (c)  Alex Genovese   https://github.com/TuxVinyards
#   SMALL CODE SNIPPETS eg the function printColor MAY BE USED  
#   PERMISSIVELY in projects as MIT or similar, providing CLEAR ATTRIBUTIONS are shown.
# 	Otherwise:  
#   Licence  GPL3   https://www.gnu.org/licenses 
##  qqX - quickemu quickget X terminal project   

## ShellCheck global disables:
# https://www.shellcheck.net/wiki/SC2242 as it clashes with use of exit traps used to keep mouse click scripts open
# And SC1090,SC2024, SC154 for necessity of dynamic file sourcing

#  shellcheck disable=SC2242
#  shellcheck disable=SC1090 
#  shellcheck disable=SC2034
#  shellcheck disable=SC2154 

show_msg_pid_found() {
      printColor "  WARNING:  QEMU may be running this machine elsewhere" 
      printf "\n\n  A .pid file '%s.pid' has been found in the Distro Folder "  "$VM_InstanceName"
      if [[ $(pgrep -x kvm) ]]; then printColor "\n\n and KVM VIRTUAL MACHINE ACTIVITY has been DETECTED "
      else printf " \n\n  but as no KVM activity has been detected, this file can probably be deleted."
      fi
      printf "\n\n  [enter] to return and/or to open File Manager and check \n\n"
      read -rp "  >  "
}


vm_pid_kill_menu() {

  tput civis

	# WAIT for background load & QEMU messages to appear before showing menu (unless reloading)
	if [[ $KillPID_Menu_Exited ]]; then  KillPID_Menu_Exited=
  elif [[ $BreakAtVerboseArgs ]]; then BreakAtVerboseArgs= ; return
  elif [[ $Mounted_ISO_Return ]]; then sleep 0.5 ; return
  else  sleep 2 
  fi
  
  # Qemu SHOULD write a .pid file while it is running & remove it when not  (Uses quickemu Var Names)
  # But from ver 1.6.02 there is a theoretical possibility of users customising out the call line: 
  # eg -pidfile ubuntu-22.04/ubuntu-22.04.pid etc being removed, so do belt & braces check for the PID  
  InstancePID="$(cat "${VMDIR}/${VMNAME}.pid" 2> /dev/null)"
  [[ ! $InstancePID ]] && InstancePID="$(pgrep "${VM_InstanceName:0:15}")"

  SpicyPID="$(pgrep spicy)"

  if [[ ! $InstancePID ]]; then 
    # if instance didn't boot but Spicy did, then close the Spicy connect dialog window
    [[ $SpicyPID ]]  && kill "$SpicyPID" 2>/dev/null &
  else
    [[ $UseCustomBootArgs ]] && printColor "  STARTING CUSTOM BOOT SEQUENCE:  \n"
    sleep  "$P_Kill_WaitSecs"   
    printColor "\n  Quickemu instance %s on PID:  %s  %s"  "$VM_InstanceName"  "$InstancePID"  "$BootAlert"
    printColor  "\n\n  [k] force close the Quickemu instance   "
    if [[ $SpicyPID ]]; then 
      SpicyReStartCmd="$(ps --no-headers -o cmd "$SpicyPID")"
      printColor " [r] reload Spicy window (if closed)"
    fi
    printf "\n\n"
    tput cnorm
  fi

  # return to menu requires VM to be shutdown first
  # run a check every second (-t 1)

  while true ; do 

    read -rp  "  >  " -t 1  KillPID_Menu

    if [[ $KillPID_Menu == "k" ]]; then 

      printf "\n\n"
      if [[ $( ps -p "$InstancePID" --no-headers 2>/dev/null) ]]; then
        [[ $SpicyPID ]] && kill "$SpicyPID" 2>/dev/null &
        kill "$InstancePID" 2>/dev/null &
      fi
      sleep 3
      printf "\n\n"
      tput cnorm
      break

    elif [[ $KillPID_Menu == "r" ]]; then 

      if [[ ! $(pgrep spicy) ]]; then 
        eval "$SpicyReStartCmd"
        sleep 2
        SpicyPID="$(pgrep spicy)"
      fi

    else

      if [[ ! $( ps -p "$InstancePID" --no-headers 2>/dev/null) ]]; then 
        tput cnorm 
        break 
      else
        #  Erase text and adjust cursor:   "\e[1A\r"  "\e[2K\r"  etc    See https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797
        printf "\r"
      fi

    fi

  done

  KillPID_Menu=
  KillPID_Menu_Exited=1
  P_Kill_WaitSecs="$P_Kill_WaitSecs_PreSet"
  refresh_and_load_quickemu_sources
  refresh_conf_vars_and_values

}	


show_main_menu_header () {

  [[ $InstancePID ]] && [[ ! $(cat "${VMDIR}/${VMNAME}.pid" 2>/dev/null) ]] && InstancePID=

  printf "\033c"
  show_qqX_title_bar   
  printf "\n"
  printColor "    %s " "$VM_InstanceName" 

  #  Default_VM_Folder, as defined in settings.  Highlight if using non-default or current (pwd).
  #  See if using a Live ISO boot  (as in function_print_conf_array) or if is a new install without .qcow disk

  if [[ $fixed_iso ]]; then Mounted_ISO="$fixed_iso" ; fixed_iso= ; fi
  if [[ $Mounted_ISO ]]; then Mounted_ISO_DisplayName="${Mounted_ISO##*/}" ; fi

  LiveBoot=
  if  [[  ! -e "$MainDrive" && ! -e "$IsoImg" ]]; then  BootAlert="(Drives CHANGED or NOT FOUND - Reload VM?)" 
  elif  [[  ! -e "$MainDrive" ]]; then  BootAlert="(New: Std ISO Boot. Main Drive yet to be created)" ; LiveBoot=1
  elif  [[  ! $(du -b -t 1000000 "$MainDrive" 2>/dev/null) ]]; then  BootAlert="(Live: ISO/IMG Boot. Distro Non-installed)"  ; LiveBoot=1
  elif  [[  $Mounted_ISO ]]; then  BootAlert="(Mounted ISO: $Mounted_ISO_DisplayName)" 
  else  BootAlert= 
  fi

  [[ $VM_Conf_Dir ]] && printf "  @   %s"  "$VM_Conf_Dir"
  printf "   %s" "$BootAlert"  
  printf "\n"

  [[ $KVM_MSR_Error ||  $Show_MSR_Warnings  || $MSR_Warnings || $Verbose_MSR_dialog ]] && print_kvm_status_warnings

  # Note .conf won't exist at first load, at VM selector menu

  if [[ ! $NewFileTuneUp && ! $NewFileTuneUp_JustDone ]] && [[ -e $VM_Conf_File ]] && [[ ! -e "$MainDrive" && ! -e "$IsoImg" ]] ; then 
    printColor "\n    ERROR  Check .conf Drive & Iso Img settings against the VM folder contents \n"
  fi

  if stat "$VM_Conf_Dir/$VM_Conf_File" 2>/dev/null | grep -q "symbolic" ; then 
    printf "\n  Symbolically linked to real path %s \n" "$(realpath "$VM_Conf_Dir/$VM_InstanceName")"
  fi

}

# When a VM_InstanceName exists, check the VM disk is not corrupt  (quickemu default name only)
# https://qemu.readthedocs.io/en/v7.2.2/tools/qemu-img.html#cmdoption-qemu-img-commands-arg-check

function check_disk_is_okay {

  local PrintErrors=

  for CheckArg in "$@" ; do 
    if [[ $CheckArg == "PrintErrors" ]]; then PrintErrors=1 ; shift ; fi
  done

  if [[ $1 && ! $2 ]]; then

    DiskCheckFolderName="$(dirname "$1")"
    DiskCheck_Disk="$(basename "$1")"

  else

    if [[ $1 ]]; then DiskCheckFolderName="$1" ; else DiskCheckFolderName="$VM_InstanceName"; fi
    if [[ $2 ]]; then DiskCheck_Disk="$2" ; else DiskCheck_Disk="disk.qcow2"; fi

  fi

  DiskChkExitCode=
  DiskChkStatus=

  if [[ -e "$DiskCheckFolderName/$DiskCheck_Disk" ]]; then

    # Disk won't exist if new (or named differently REVIEW )
    # Qemu-img with '-q' only outputs if error & on outputs on stderr   The exit status remains separately recorded.

    if [[ $PrintErrors ]]; then  "$QEMU_IMG" check -q "$DiskCheckFolderName/$DiskCheck_Disk"

    else "$QEMU_IMG" check -q "$DiskCheckFolderName/$DiskCheck_Disk"  2>/dev/null ; fi

    # Note "Okay"  is also used as a flag  > caution if changing   # REVIEW  could also be flagged using:
    # DiskChkMsg="$("$QEMU_IMG" check -q "$DiskCheckFolderName/$DiskCheck_Disk" 2>&1)" 

    case "$?" in 

      0) DiskChkStatus="Okay" ;;

      1) DiskChkStatus="Check not completed because of internal errors" ;;

      2) DiskChkStatus="Check completed, image is corrupted" 
         DiskChkExitCode=2 ;;

      3) DiskChkStatus="Check completed, image has leaked clusters, but is not corrupted" 
         DiskChkExitCode=3  ;;

      63) DiskChkStatus="Checks are not supported by the image format -- not qcow2 ??" ;;

    esac

  fi

}

## filter for 'ERRORS' that changes in QEMU might throw up and that WE WANT TO IGNORE  (see main settings)

filter_and_flag_qemu_errors () {

  if [[ ! -e "$QemuErrorLog" ]]; then  printColor "\n\n  Internal ERROR:  QemuErrorLog not found.  A qqX re-start may be needed."  
  
  elif [[ $(cat "$QemuErrorLog" 2>/dev/null) ]]; then 

    QemuErrorAlert=1

    if [[ "${QemuErrorFilter[*]}" ]]; then
      for ErrChk in "${QemuErrorFilter[@]}"; do
        if grep -q -s "$ErrChk" "$QemuErrorLog" ; then QemuErrorAlert= ; return ; fi
      done
    fi

    if [[ "${QemuError_VM_Filter[*]}" ]]; then
      for ErrChk in "${QemuError_VM_Filter[@]}"; do
        if grep -q -s "$ErrChk" "$QemuErrorLog" ; then QemuErrorAlert= ; return ; fi
      done
    fi

  else  QemuErrorAlert=
    
  fi

}


function_delete_Selected_VM () {

  if [[ ! $1 && ! $2 ]]; then
    # Normally: VM_InstanceName="${VM_Conf_File/.conf}"
    printColor "\n\n  Internal Params: VM Name & VM config file (NO PATH) must be given \n\n " 
    sleep 2 ;  return
  fi

  if [[ ! -d "$1" ]] || [[ ! -e "$2" ]]; then
    printColor "\n\n  Internal Params: VM Name & VM config file (NO PATH) must be given \n\n " 
    printColor "\n\n  Internal Params: VM Name / VM config file  NOT FOUND  \n\n " 
    sleep 2 ;  return
  fi

  if [[ $(type -p gio 2>/dev/null) ]]; then TrashingAvailable=1 ; else TrashingAvailable= ; fi

  if stat "$1" 2>/dev/null | grep -q "symbolic" ; then 
    printColor "\n\n  Symbolically linked to real path "; printf "%s " "$(realpath "$1")"
    printColor "\n\n  REMOVING LINKS ONLY - VM CONTENT REMAINS AT REALPATH \n"
  fi

  vm_selector_init_common
  i=0
  ConnectedLinks=
  while [[ ${VM_Array[$i,0]} ]] ; do
    if [[ $1 == "$(basename "${VM_Array[$i,1]}" .conf)" ]] && [[ $(pwd) != "${VM_Array[$i,0]}" ]] &&\
    stat "${VM_Array[$i,0]}/$(basename "${VM_Array[$i,1]}" .conf)" | grep -q "symbolic"; then

      LinkPathName="${VM_Array[$i,0]}/$(basename "${VM_Array[$i,1]}" .conf)" 
      TestPathName="$(stat -c %N "$LinkPathName" | cut -d '>' -f2 )"
      TestPathName="${TestPathName/" '"/}"
      TestPathName="${TestPathName/"'"/}"
      if [[ $TestPathName == "$(pwd)/$1" ]]; then
        printColor "\n\n  WARNING: connected VM LINKS have been found and they will also need deleting:"
        printf "\n\n  >>>  %s\n" "$LinkPathName"
        ConnectedLinks=1
      fi
    fi
    ((i+=1))
  done

  printColor "\n\n  Folder: %s" "$1"
  printColor "  &  File: %s  to be deleted?"  "$2"
  if [[ $ConnectedLinks ]]; then
    printf  "\n\n  TO DELETE THIS VM, removal of BOTH the above FOLDER/FILE and the CONNECTED LINKS is required."
  else
    printf  "\n\n  To delete this VM, removal of the above folder/file is sufficient."
  fi
  printf "\n\n  Select [n] to manually delete using a file manager, if there are certain files that you want to keep."
  printColor "\n\n\n  Folder content: \n\n"
  ls "$1"

  if [[ $TrashingAvailable ]]; then 
    printColor "\n\n  [enter] safely move the folder & file to the recoverable trash bin"  
    printf "\n\n  [n] keep   [y] yes, PERMANENTLY, I have back-ups ..."
  else
    printColor "\n\n  [enter] use the file manager to move things the trash bin "
    printf "\n\n  [y] yes, PERMANENTLY, I have back-ups ..."
  fi

  printf "\n\n"
  read -rp "  >  "   Delete_VM_Option

  if [[ $Delete_VM_Option == "y" ]]; then 

    printf "\n\n  Folder & .conf file being deleted ... "
    rm -f -r "$1"  
    rm -f "$2"

  else

    if [[ $TrashingAvailable ]] && [[ $Delete_VM_Option != "n" ]]; then
      printf "\n\n  Moving files to the bin ... "
      gio trash "$1"
      gio trash "$2"
    else  printf "\n\n  NOT deleted ... "
    fi  # https://specifications.freedesktop.org/trash-spec/trashspec-latest.html

  fi

  printColor "\n\n  [enter] to return or continue \n\n" 
  read -rp "  > "

  ByPass_VM_Array_Selector=
  ByPass_VM_Array_Loader=
  VM_InstanceName=
  VM_Conf_Dir=
  VM_Conf_File=
  MainDrive=
  IsoImg=
  NewFileTuneUp=
  NewFileTuneUp_JustDone=
  cd "$Default_VM_Folder" || DefaultFolderError=1
  refresh_sources_and_load_VM_arrays

}


function_rename_conf_dirnames () {  

  if [[ ! $1 ]]; then
    # Normally: "${Mv_NewName}.conf"  "VM Old Name"  "$Mv_NewName"  And conf has been backed up.  
    printColor "\n\n  Conf Rename Internal Params: VM config file (NO PATH) must be given"
    printf "\n\n  Function to be called from main menu, where pwd == VM_Conf_Dir \n\n" 
    sleep 2 ;  return
  fi

  mapfile -t ConfRenameArray < "$1"
  printf "" > "$1"

  for Line in "${ConfRenameArray[@]}"; do
    [[ "$Line" == *"$2"* ]] && Line="${Line//"$2"/"$3"}"
    printf "%s\n" "$Line" >> "$1"
  done
}

list_current_folder_instance_names () {

  CurrentFolderNames=()
  CurrentFolderNameError=
  mapfile -t CurrentFolderContent <<< "$(ls 2>/dev/null)"
  for Name in "${CurrentFolderContent[@]}"; do [[ -d "$Name" ]] && CurrentFolderNames+=("$Name"); done

  printf "\n  Containing:   "
  if [[ ! ${CurrentFolderNames[*]} ]]; then printColor " NONE FOUND \n\n" 
  else 
    printf "\n\n" 
    print_quickget_and_folder_choices  "CurrentFolderNames"  6 
  fi
}


move_rename_Selected_VM () {  

  if [[ ! $1 && ! $2 ]]; then
    # Normally: VM_InstanceName="${VM_Conf_File/.conf}"
    printColor "\n\n  Move Rename Internal Params: VM Name & VM config file (NO PATH) must be given"
    printf "\n\n  Function to be called from main menu, where pwd == VM_Conf_Dir \n\n" 
    sleep 2 ;  return
  fi

  if [[ ! -d "$1" ]] || [[ ! -e "$2" ]]; then
    printColor "\n\n  Internal Params: VM Name & VM config file (NO PATH) must be given \n\n " 
    printColor "\n\n  Move Rename Internal Params: VM Name / VM config file  NOT FOUND " 
    printf "\n\n  Function to be called from main menu, where pwd == VM_Conf_Dir \n\n" 
    sleep 2 ;  return
  fi

  MoveFail=
  Move_VM_Option=
  MvTargetIsLinked=

  if stat "$1" 2>/dev/null | grep -q "symbolic" ; then 
    printColor "\n\n  Symbolically linked to real path "; printf "%s " "$(realpath "$1")"
    printColor "\n\n  DELETE LINKS and REMAKE instead - VM CONTENT REMAINS AT REALPATH \n"
    MvTargetIsLinked=1
  fi

  printColor "\n\n  Folder: %s  & file: %s  to be Renamed or Moved" "$1" "$2"
  printf  "\n\n  Renames VM's in Current Folder or Moves VM's and Renames if required. "
  printf "\n\n  Rewrites all the config internals as needed, avoiding manual tedium and errors ..."
  printf "\n\n  Also allows Symbolic Link creation to VM with refs in another category folder" 
  printf "\n\n"
  [[ ! $MvTargetIsLinked ]] && printColor "  [r] to rename  [m] to move  [ln] make symbolic links"
  printf "  [b] to go back"   
  printf "\n\n"
  read -rp "  >  "   Move_VM_Option

  if [[ $Move_VM_Option == "m" || $Move_VM_Option == "mv" || $Move_VM_Option == "ln" ]]; then 

    if [[ $Move_VM_Option == "ln" ]]; then MakeLinksOnly=1 ; else MakeLinksOnly= ; fi

    printf "\n  Folder '%s' & .conf file to be MOVED and edited or Linked"  "$1"
    printf "\n\n  For new preset group folders, edit the main settings" 
    printf "\n\n  Current Folder: '%s' \n" "$(pwd)"
    show_current_group_folder_list

    while true; do
      
      printColor "\n\n  [number] select a different group folder "
      printf " [b] to go back\n\n"
      read -rp  "  >  "  Move_FolderOption

      case "$Move_FolderOption" in

        b)
          Move_FolderOption= ; Move_VM_Option=
          return
        ;;

        [0-9]|[0-9][0-9]) 
          Mv_NewConf_Dir="${VM_Folder_List[Move_FolderOption]}" 
          if [[ "$(pwd)" == "$Mv_NewConf_Dir" ]]; then  Move_FolderOption= 
          else 
            printf "\n\n  Selected: '%s' "  "$Mv_NewConf_Dir"  
          fi
          printColor "\n\n  [enter] to confirm " ; printf " [r] re-select \n\n"
          [[ $Move_FolderOption ]] && read -rp "  >  " Move_FolderOption
          if [[ $Move_FolderOption == "r" ]]; then Move_FolderOption= 
          elif [[ "$(pwd)" == "$Mv_NewConf_Dir" ]]; then printf "\n  ERROR  Same Folder "; Move_FolderOption= 
          else break
          fi
        ;;

      esac

    done

    Mv_OldFolderPath="$(realpath "$VM_InstanceName")"
    Mv_OldConfPath="$(realpath "${VM_InstanceName}.conf")"

    Move_VM_Option="r"
    if cd "$Mv_NewConf_Dir"; then printf "\n  Selected target folder '%s'\n"  "$Mv_NewConf_Dir"
    else printColor "\n ERROR changing folder \n" ; Move_VM_Option= 
    fi

  fi

  if [[ $Move_VM_Option == "r" ]]; then  

    list_current_folder_instance_names

    while true; do

      Mv_NewName=
      CurrentFolderNameError=
      printf "\n\n\n  Selected Distro '%s' & .conf file to be RE-NAMED and edited or Linked"  "$1"
      printColor "\n\n  Please give a new VM name" ; [[ $Mv_NewConf_Dir ]] && printf "  or [n] no-change  [ln] make link"
      printf "\n\n  eg. tux-33-alpha  emu-44-mate  or [b] to go back \n\n"   
      read -rp "  >  "  Mv_NewName 

      [[ ! $Mv_NewName || $Mv_NewName == "n" || $Mv_NewName == "ln" ]] && Mv_NewName="$VM_InstanceName"  && break
      
      for Name in "${CurrentFolderNames[@]}"; do [[ $Mv_NewName == "$Name" ]] && CurrentFolderNameError=1; done
      if [[ $CurrentFolderNameError ]]; then printf "\n\n  ERROR  Name already exists" ; else break ; fi

    done

    if [[ $Mv_NewName == "b" ]]; then  Move_VM_Option= ; Mv_NewName= ; Move_FolderOption= ; Move_VM_Option= ; Mv_NewConf_Dir= ; return ; fi

    Mv_NewName_Return=
    if [[ $Mv_NewName != "$VM_InstanceName" ]]; then printf "\n\n  Renaming to '%s' " "$Mv_NewName"
    elif [[ $MakeLinksOnly ]]; then  printf "\n\n  Making link to '%s' " "$VM_InstanceName"
    else printf "\n\n  Keeping old name '%s' " "$Mv_NewName"
    fi
    printColor "\n\n  [enter] to make this happen  [b] to go back \n\n"
    read -rp "  >  "  Mv_NewName_Return

    if [[ $Mv_NewName_Return ]]; then  
      Mv_NewName_Return= ; Move_VM_Option= ; Mv_NewName= ; Move_FolderOption= ; Move_VM_Option= ; Mv_NewConf_Dir= ; return
    fi
    if [[ $MakeLinksOnly ]]; then
      if [[ $Mv_NewConf_Dir ]]; then 
        ln -s "$Mv_OldFolderPath" "$Mv_NewConf_Dir/$(basename "$Mv_OldFolderPath")" || MoveFail=1
        ln -s "$Mv_OldConfPath" "$Mv_NewConf_Dir/$(basename "$Mv_OldConfPath")" || MoveFail=1
      fi
    else
      if [[ $Mv_NewConf_Dir ]]; then 
        mv "$Mv_OldFolderPath" "$(basename "$Mv_OldFolderPath")" || MoveFail=1
        mv "$Mv_OldConfPath" "$(basename "$Mv_OldConfPath")" || MoveFail=1
        set -- "$(basename "$Mv_OldFolderPath")" "$(basename "$Mv_OldConfPath")" 
      fi
      if [[ $Mv_NewName != "$VM_InstanceName" ]]; then
        if [[ ! $MoveFail ]] && cp "$2" "$1/${2}.rename.old.txt" ; then    
          mv "$1" "$Mv_NewName" || MoveFail=1
          mv "$2"  "${Mv_NewName}.conf" || MoveFail=1
        fi
        if [[ ! $MoveFail ]] ; then function_rename_conf_dirnames "${Mv_NewName}.conf"  "$1"  "$Mv_NewName" ; fi
      fi
    fi
  
  else  

    Move_VM_Option= ; Move_FolderOption= ; Move_VM_Option= ; Mv_NewConf_Dir= ; return

  fi

  if [[ $MoveFail ]]; then printColor "\n  Hmm. Something went wrong.  \n"  ; else printColor "\n  Success  '%s'\n"  "$(pwd)" ; fi
  list_current_folder_instance_names

  ConfLine="$(grep -s 'macos_release=' "${Mv_NewName}.conf")"
  if [[ $ConfLine ]]; then
    printColor "\n\n  MAC OS %s.conf file may need manually editing, if the release doesn't match: %s " "$Mv_NewName"  "$ConfLine"
  fi

  printColor "\n\n  [enter] to return or continue \n\n" 
  read -rp "  > "

  if [[ ! $MoveFail && $Mv_NewConf_Dir ]]; then

    QemuErrorLog="$Mv_NewConf_Dir/$Mv_NewName/${Mv_NewName}.qemu.error.log"
    ByPass_VM_Array_Selector=
    ByPass_VM_Array_Loader=
    SelectArrayError=
    VM_InstanceName=
    VM_Conf_Dir=
    VM_Conf_File=
    MainDrive=
    IsoImg=
    NewFileTuneUp=
    NewFileTuneUp_JustDone=
    MoveFail=
    Move_FolderOption=
    Move_VM_Option=
    Mv_NewName=
    Mv_NewConf_Dir=
    Mv_NewName_Return=

  elif [[ ! $MoveFail ]]; then

    ByPass_VM_Array_Selector=1
    VM_Renamed=1
    SelectArrayError=
    VM_InstanceName="$Mv_NewName"
    VM_Conf_File="${Mv_NewName}.conf"
    QemuErrorLog="$VM_Conf_Dir/$VM_InstanceName/${VM_InstanceName}.qemu.error.log"
    MainDrive=
    IsoImg=
    NewFileTuneUp=
    NewFileTuneUp_JustDone=
    MoveFail=
    Move_FolderOption=
    Move_VM_Option=
    Mv_NewName=

  fi

  # Current behaviour, if moved, is to return to the VM selector and see the results of what we have done.
  # Or return back to menu if just renamed, but via the main loop and the configs reloader  

  [[ $GeneralLoopCheck ]] && printf "\n\n Move Finish:" &&  dev_loop_check

}

read_x86_tiano_vars_list () {

  # current std list
  String="$(grep -A 20 -m 1 'ovmfs=' /usr/bin/quickemu | grep '"')"    

  String="$(tr -cd '[:print:]' <<< "$String")"
  String="${String//'ovmfs=('/}"
  String="${String//','/' '}"

  # shellcheck disable=SC1003 
  String="${String//'\'/' '}"
  String="$(tr -s '[= =]' <<< "$String")"

  # shellcheck disable=SC2206
  Tiano_x86_FilesList=($String)
  Tiano_x86_CodeList=()
  Tiano_x86_VarsList=()

  i=0    
  while [[ "${Tiano_x86_FilesList[i]}" ]]; do Tiano_x86_CodeList+=("${Tiano_x86_FilesList[i]}"); ((i+=2)); done
  i=1    
  while [[ "${Tiano_x86_FilesList[i]}" ]]; do Tiano_x86_VarsList+=("${Tiano_x86_FilesList[i]}"); ((i+=2)); done

}


refresh_tiano_vars () {  

  RtvBack= ; RtvArm=
  read_x86_tiano_vars_list

  if [[ $RunRtvCheck || $RtvManualOnly ]]; then RtvText=1 ; else RtvText= ; fi

  if [[ $RtvText ]]; then

    printColor "\n\n  In cases when distro boot sequences get stuck in unwanted loops or behaviours, this may help:"
    printf "\n\n  Backups will be made, in case you need to revert, as *.fd.old etc \n\n  Your *VMF_VARS.fd file(s) will be reinstalled."
    if [[ "$VM_InstanceName" == *macos* ]]; then 
      printf "\n\n  MacOS refreshes require an internet connection. The small boot drive 'OpenCore.qcow2' is also needed."
      printf "\n\n  For security reasons, these Mac specific files should generally be updated at regular intervals...."
    fi

    if [[ $(ls "$VM_Conf_Dir/$VM_InstanceName/AAVMF"* 2>/dev/null) ]]; then
      RtvArm=1
      if [[ ! $RtvArmFolder ]]; then
        printf  "\n\n  Using Standard Folder '/usr/share/AAVMF' >> Variations may be placed in main settings"
        RtvArmFolder="/usr/share/AAVMF"
      else
        printf  "\n\n  Using Folder '%s' >>  From variation placed in main settings" "$RtvArmFolder"
      fi
    fi 

    printColor  "\n\n  [enter] to continue"
    printf  "  [b] to go back "
    read -rp "  >  "  RtvBack

  fi

  if [[ $RtvBack ]]; then  printf "\n\n  Returning ... " ; sleep 1

  else

    if [[ $RtvArm ]]; then 

      AA_VarsList=("AAVMF_VARS.fd"  "AAVMF32_VARS.fd"  "AAVMF_VARS.ms.fd"  "AAVMF_VARS.snakeoil.fd")

      [[ $RtvText ]] && printf "\n\n  Checking: %s" "${AA_VarsList[*]}"

      for AA_Var in "${AA_VarsList[@]}"; do
        if [[ -e "$VM_Conf_Dir/$VM_InstanceName/$AA_Var" ]]  &&  [[ -e "/usr/share/AAVMF/$AA_Var" ]]; then
          mv "$VM_Conf_Dir/$VM_InstanceName/$AA_Var" "$VM_Conf_Dir/$VM_InstanceName/${AA_Var}.old"
          cp -f "/usr/share/AAVMF/$AA_Var" "$VM_Conf_Dir/$VM_InstanceName/$AA_Var"
          [[ $RtvText ]] && printColor "\n\n  Reset/Installed '%s' "  "$AA_Var"
        fi
      done

    elif [[ "$VM_InstanceName" == *macos* ]]; then

      RtvMacGet="Okay"

      [[ -e "$VM_Conf_Dir/$VM_InstanceName/OpenCore.qcow2" ]] &&  \
      mv "$VM_Conf_Dir/$VM_InstanceName/OpenCore.qcow2" "$VM_Conf_Dir/$VM_InstanceName/OpenCore.qcow2.old"

      [[ -e "$VM_Conf_Dir/$VM_InstanceName/OVMF_CODE.fd" ]] &&  \
      mv "$VM_Conf_Dir/$VM_InstanceName/OVMF_CODE.fd" "$VM_Conf_Dir/$VM_InstanceName/OVMF_CODE.fd.old"

      [[ -e "$VM_Conf_Dir/$VM_InstanceName/OVMF_VARS-1920x1080.fd" ]] &&  \
      mv "$VM_Conf_Dir/$VM_InstanceName/OVMF_VARS-1920x1080.fd" "$VM_Conf_Dir/$VM_InstanceName/OVMF_VARS-1920x1080.fd.old"

      # as per quickget 4.9.2

     [[ $RtvText ]] && printf "\n\n  Checking ..."

      wget -t 3 -T 2 -o "$VM_Conf_Dir/$VM_InstanceName/rtv.log" "https://github.com/kholia/OSX-KVM/raw/master/OVMF_VARS-1920x1080.fd" \
      -O "$VM_Conf_Dir/$VM_InstanceName/OVMF_VARS-1920x1080.fd" || RtvMacGet="Fail"

      [[ $RtvText ]] && printf "....."

      wget -t 3 -T 2 -a "$VM_Conf_Dir/$VM_InstanceName/rtv.log" "https://github.com/kholia/OSX-KVM/raw/master/OVMF_CODE.fd" \
      -O "$VM_Conf_Dir/$VM_InstanceName/OVMF_CODE.fd" || RtvMacGet="Fail"
      
      [[ $RtvText ]] && printf "........ \n\n"

      wget -t 3 -T 2 -a "$VM_Conf_Dir/$VM_InstanceName/rtv.log" "https://github.com/kholia/OSX-KVM/raw/master/OpenCore/OpenCore.qcow2" \
      -O "$VM_Conf_Dir/$VM_InstanceName/OpenCore.qcow2" || RtvMacGet="Fail"

      [[ $RtvText ]] && grep -v '\.\.\.\.\.\.\.' "$VM_Conf_Dir/$VM_InstanceName/rtv.log" 

      echo "$RtvMacGet" > "$VM_Conf_Dir/$VM_InstanceName/rtv.status.log"

      [[ $RtvText ]] && printColor "\n  Update:  %s" "$RtvMacGet"

    else

      i=0 
      while [[ "${Tiano_x86_VarsList[i]}" ]]; do

        x86_VarPath="${Tiano_x86_VarsList[i]}"
        x86_VarPath="${x86_VarPath//'"'/}"

        x86_Var="$(basename "${Tiano_x86_VarsList[i]}")"
        x86_Var="${x86_Var//'"'/}"

        # For reasons unexplained, quickget 4.9.2 and previous go through the whole list from beginning to end,
        # and selects the last available option, not the first. Whatever the rationale was, it's probably best to 
        # leave things as they are. At least for now.  REVIEW 
        # Quickemu should re-install the 'correct' vars file if the current one(s) is(are) removed.  

        if [[ -e "$VM_Conf_Dir/$VM_InstanceName/$x86_Var" ]]; then 
          mv "$VM_Conf_Dir/$VM_InstanceName/$x86_Var" "$VM_Conf_Dir/$VM_InstanceName/${x86_Var}.old"
          [[ $RtvText ]] && printColor "\n\n  Reset '%s' >> Quickemu will now auto-update your VM on its next boot"  "$x86_Var"
        fi

        ((i+=1))
      done

    fi

    date +%s > "$VM_InstanceName/rtv.date.txt"

    if [[ $RtvText ]]; then
      printf "\n\n  [enter] to return \n\n "
      read -rp "  >  "
    fi
    
  fi
}

clear_custom_boot_vars () {
  MenuCustomSystem=
  MenuCustomMachine=
  MenuCustomSystemBaseName=
  ShowDefault_Hybrid=
  ShowCustomBootMenu=
  ForceCustomBootMenu=
}


custom_boot_file () {

  clear_custom_boot_vars

  if [[ $1 == "create" ]]; then 

    printColor "\n\n  Utility to copy QEMU args list from the last qemu boot formula"
    printf "\n\n  Boot in 'Verbose mode' is sufficient. Actual boot is not required."
    printf "\n\n  Full details are viewable online at \n\n  https://github.com/TuxVinyards/qqX/wiki/Custom-Qemu-boot-parameters"

    if [[ ! -e "$VM_InstanceName/Qemu_ShortArgs_List.txt" ]]; then
      printf "\n\n  NO ARGS FILE yet present "
    fi

    CreateCustom=
    printColor "\n\n\n  [enter] to proceed    [b] to go back   [w] view wiki  \n\n" 
    read -rp "  >  "  CreateCustom

    if [[ $CreateCustom == "b" ]]; then return

    elif [[ $CreateCustom == "w" ]]; then

      nohup &> /dev/null  "$WebBrowser"  "https://github.com/TuxVinyards/qqX/wiki/Custom-Qemu-boot-parameters"  &  

    elif [[ -e "$VM_InstanceName/Qemu_ShortArgs_List.txt" ]]; then
     
        printf "\n\n  Creating Custom Boot file \n\n"
        cp -f "$VM_InstanceName/Qemu_ShortArgs_List.txt"  "$VM_InstanceName/Qemu_ShortArgs_Custom.txt" 
        sleep 1.5
        
    fi     

  elif [[ $1 == "delete" ]]; then 
 
    printColor "\n\n  Utility to delete existing custom qemu boot formula"
    printf "\n\n  Full details are viewable online at \n\n  https://github.com/TuxVinyards/qqX/wiki/Custom-Qemu-boot-parameters"

    if [[ ! -e "$VM_InstanceName/Qemu_ShortArgs_List.txt" ]]; then
      printf "\n\n  NO CUSTOM BOOT FILE present "
    fi

    DeleteCustom=
    printColor "\n\n\n  [enter] to proceed    [b] to go back   [w] view wiki  \n\n" 
    read -rp "  >  "  DeleteCustom

    if [[ $DeleteCustom == "b" ]]; then return

    elif [[ $DeleteCustom == "w" ]]; then

      nohup &> /dev/null  "$WebBrowser"  "https://github.com/TuxVinyards/qqX/wiki/Custom-Qemu-boot-parameters"  &  

    elif [[ -e "$VM_InstanceName/Qemu_ShortArgs_Custom.txt" ]]; then
     
        printf "\n\n  Deleting Custom Boot file, renaming as .old ...\n\n"
        mv "$VM_InstanceName/Qemu_ShortArgs_Custom.txt"  "$VM_InstanceName/Qemu_ShortArgs_custom.old.txt" 
        sleep 1.5
        
    fi     

  else  printColor "\n\n  Internal ERROR:  parameter required for function custom_boot_file \n\n"

  fi

  SettingsFileAdjusted=1
  refresh_sources_and_load_VM_arrays

}


iso_select_mount_and_boot () {

  # to be run from main menu, on presumption of a VM having been selected, 
  # the standard VM vars to be in place and set up

  if [[ "$(pwd)" != "$VM_Conf_Dir" ]]; then 
    printColor "\n\n  ERROR: iso_select_mount_and_boot not running from correct folder \n\n"
  else
    IsoList=()
    mapfile -t IsoList <<< "$(ls "$VM_InstanceName"/*.iso 2>/dev/null)"

    printColor "\n\n  ISO formated disk images may be copied into the individual VM folder"
    printf "\n\n  One or more may be added.  If more than one, an ISO should be selected from the list."
    printf "\n\n  Current Quickemu code is retricted to one only to be present as mounted at a time."

    printf "\n\n\n  To boot from a selected ISO, press the 'esc' key when the start up screen appears."
    printf "\n\n  To auto-mount an ISO when the VM is selected, set 'fixed_iso=\"VM_InstanceName/name.iso\"' in the .conf file"
    printf "\n\n  A 'live boot' ISO such as from https://gparted.org/download.php is normally required for partition management."
    printf "\n"

    if [[ $LiveBoot ]]; then
      printf "\n\n  CAUTION: You are already standard booting from an ISO. "
      printf "\n\n  The distro has not yet been installed to the disk."
    fi

    if [[ ! ${IsoList[*]} ]]; then 
      printColor "\n\n  NONE FOUND:  An ISO formated disk image should be copied into the individual VM folder"
    elif [[ ! ${IsoList[1]} ]]; then 
      printColor "\n\n  Single ISO FOUND:  %s" "${IsoList[0]}"
    else
      printf "\n\n"
      print_quickget_and_folder_choices  IsoList
    fi

    if [[ $Mounted_ISO ]]; then printColor "\n\n  %s  is currently mounted" "$Mounted_ISO"
    else printColor "\n\n  No ISO is currently mounted"
    fi

    IsoSelect=
    printf "\n\n" 
    if [[ $LiveBoot ]]; then
      printColor "  [b] to go back"
    else
      if [[ ${#IsoList[*]} -eq 1 ]]; then  printColor "  [m] to mount/unmount " 
      elif [[ ${#IsoList[*]} -gt 1 ]]; then  printColor "  [number] to select and mount/unmount " 
      fi
      printf "  [b] to go back"
    fi

    printf "\n\n"
    read -rp "  >  "  IsoSelect

    if [[ $IsoSelect == "m" ]]; then  
      if [[ ! $Mounted_ISO ]]; then Mounted_ISO="${IsoList[0]}" ; else Mounted_ISO= ; fi
    elif [[ "$IsoSelect" == [1-9] || "$IsoSelect" == [1-9][0-9] ]]; then 
      ((IsoSelect-=1)) 
      if [[ ! $Mounted_ISO ]]; then Mounted_ISO="${IsoList[IsoSelect]}" 
      elif [[ $Mounted_ISO == "${IsoList[IsoSelect]}" ]]; then Mounted_ISO=
      elif [[ $Mounted_ISO != "${IsoList[IsoSelect]}" ]]; then Mounted_ISO="${IsoList[IsoSelect]}"
      fi
    fi
  fi
}