#!/bin/bash

# qqX helper file for developers:
# Use to easy update desktop installed versions of qqX 
# with modified scripts and settings from your source folder (edit as required)

SourceFolder="$HOME/qqX"   

cd "$SourceFolder"  || echo " ERROR  changing to Source Folder"; echo

source "qqX.system/qqX_settings_update_transposer"
source "qqX.system/Func_echo_colors"

function copy_files {

	printf "\n"
	sudo cp  qqX.main/*   /usr/share/qqX/qqX.main/  || CopyFail=1
	sudo cp  qqX   /usr/bin/qqX  || CopyFail=1
	printf "\n"
}

Counter=0

while true ; do

	if [[ $Counter == 0 ]]; then 
		printf "\033c"
		printf "\n From %s" "$SourceFolder"
		printColor "\n\n COPY the qqX script to usr/bin" 
		printColor "\n\n COPY all qqX.main scripts to /usr/share/qqX \n"  
	fi
	
	copy_files

	if [[ $CopyFail ]]; then printColor " COPY ERROR .... " ; else printf " Copied ... @ %s" "$(date +%H.%M.%S)"  ; fi
	
	printf "\n\n Terminal may be kept open. Sudo will stay usable for a while ..."
	printColor "\n\n COPY > [enter] to re-run" ; printf "    [s] qqX SETTINGS update \n\n" 
	read -rp " >  "  UpdSets
	
	if [[ $UpdSets ]]; then 
		update_old_settings_file_with_new_options 
		((Counter+=1)) 
		printColor "  [enter] to continue \n\n " 
		read -t 5 -rp "  >  "
	fi
	
	((Counter+=1)) ;  [[ $Counter -ge 4 ]] && Counter=0 ; UpdSets= ; CopyFail=
		
done

