#!/bin/bash

# qqX helper file for developers:
# Use to easy update desktop installed versions of qqX
# with modified scripts and settings from your source folder (edit as required)

# SourceFolder="$HOME/qqX"

[[ ! $SourceFolder ]] && printf " \n\n  A Source Folder must be given >> Dev's please edit this file at the top ... \n\n " && sleep 100

cd "$SourceFolder"  || echo " ERROR  changing to Source Folder"; echo

# need updating if there have been changes
source "qqX.system/qqX_settings_update_transposer"
source "qqX.system/Func_echo_colors"

#  VARIABLES for Non FHS OS packaging, also edit at start of main file 'qqX' ...
#  WiP: attention may need to be given to the qqX updater too ...
#  From qqX 1.6 onwards, a folder /usr/share/qqX should be created for the subfolder and files of qqX.main
#  And from 1.8 the subfolder qqX.builtins

qqX_Std_Bin_Dir="/usr/bin"
qqX_Std_Share_Path="/usr/share/qqX"

function copy_files {
	printf "\n"
	# remove any old and possibly obsolete and unneeded files
  [[ -d "$qqX_Std_Share_Path/qqX.main" ]] && sudo rm -r "$qqX_Std_Share_Path/qqX.main"
	sudo cp  -r qqX.main  "$qqX_Std_Share_Path/"  || CopyFail=1
	sudo cp  qqX   "$qqX_Std_Bin_Dir/qqX"  || CopyFail=1
	sudo chmod a+rx -R  "$qqX_Std_Share_Path/qqX.main"
	sudo chmod a+rx "$qqX_Std_Bin_Dir/qqX"
	source "qqX.system/qqX_settings_update_transposer"
	source "qqX.system/Func_echo_colors"
	printf "\n"
}

function copy_builtins {
	printf "\n"
	[[ -d "$qqX_Std_Share_Path/qqX.builtins" ]] && sudo rm -r "$qqX_Std_Share_Path/qqX.builtins"
	[[ -d "$qqX_Std_Share_Path/qqX.lib" ]] && sudo rm -r "$qqX_Std_Share_Path/qqX.lib"
	sudo cp -r qqX.builtins   "$qqX_Std_Share_Path/"  || CopyFail=1
	sudo chmod a+rx -R  "$qqX_Std_Share_Path/qqX.builtins"
	sudo cp -r qqX.lib   "$qqX_Std_Share_Path/"  || CopyFail=1
	sudo ln -f -s "$qqX_Std_Share_Path/qqX.lib/floatversion" "$qqX_Std_Share_Path/qqX.lib/fv"
	sudo chmod a+rx -R  "$qqX_Std_Share_Path/qqX.lib"
	source "qqX.system/qqX_settings_update_transposer"
	source "qqX.system/Func_echo_colors"
	printf "\n Builtins Copied \n"
}

Counter=0

while true ; do

	if [[ $Counter == 0 ]] && [[ ! $DevSetUpdArrOutputScrn ]]; then
		printf "\033c"
		printf "\n From %s" "$SourceFolder"
		printColor "\n\n COPY the qqX script to usr/bin"
		printColor "\n\n COPY all qqX.main scripts to /usr/share/qqX \n"
	fi

	printf "\n\n Terminal may be kept open. Sudo will stay usable for a while ..."
	printColor "\n\n COPY > [enter] for qqX scripts" ; printf "    [s] qqX SETTINGS update    [b] copy /qqX.builtins to /usr/share/qqX \n\n"
	read -rp " >  "  UpdSets

	if [[ $UpdSets ]]; then
		[[ $UpdSets == "s" ]] && update_old_settings_file_with_new_options
		[[ $UpdSets == "b" ]] && copy_builtins
		((Counter+=1))
	else
		copy_files
		if [[ $CopyFail ]]; then printColor " COPY ERROR .... \n" ; else printf " Copied @ %s \n" "$(date +%H.%M.%S)"  ; fi
	fi

	sleep 1

	((Counter+=1)) ;  [[ $Counter -ge 4 ]] && Counter=0 ; UpdSets= ; CopyFail=

done

