#!/bin/bash

# qqX helper file for developers:
# Use to easy update desktop installed versions of qqX 
# with modified scripts and settings from your source folder (edit as required)

# SourceFolder="$HOME/qqX"   

[[ ! $SourceFolder ]] && printf " \n\n  A Source Folder must be given >> Dev's please edit this file at the top ... \n\n " && sleep 100

cd "$SourceFolder"  || echo " ERROR  changing to Source Folder"; echo

# need updating if there have been changes
source "qqX.system/qqX_settings_update_transposer"
source "qqX.system/Func_echo_colors"

function copy_files {
	printf "\n"
	sudo cp  qqX.main/*   /usr/share/qqX/qqX.main/  || CopyFail=1
	sudo cp  qqX   /usr/bin/qqX  || CopyFail=1
	source "qqX.system/qqX_settings_update_transposer"
	source "qqX.system/Func_echo_colors"
	printf "\n"
}

function copy_builtins {
	printf "\n"
	sudo cp -r qqX.builtins/*   /usr/share/qqX/qqX.builtins/  || CopyFail=1
	source "qqX.system/qqX_settings_update_transposer"
	source "qqX.system/Func_echo_colors"
	printf "\n Builtins Copied \n"
}

Counter=0

while true ; do

	if [[ $Counter == 0 && ! $DevSetUpdArrOutputScrn ]]; then 
		printf "\033c"
		printf "\n From %s" "$SourceFolder"
		printColor "\n\n COPY the qqX script to usr/bin" 
		printColor "\n\n COPY all qqX.main scripts to /usr/share/qqX \n"  
	fi

	printf "\n\n Terminal may be kept open. Sudo will stay usable for a while ..."
	printColor "\n\n COPY > [enter] for qqX scripts" ; printf "    [s] qqX SETTINGS update    [b] copy /qqX.builtins to /usr/share/qqX \n\n" 
	read -rp " >  "  UpdSets
	
	if [[ $UpdSets ]]; then 
		[[ $UpdSets == "s" ]] && update_old_settings_file_with_new_options 
		[[ $UpdSets == "b" ]] && copy_builtins 
		((Counter+=1)) 
	else	
		copy_files	
		if [[ $CopyFail ]]; then printColor " COPY ERROR .... \n" ; else printf " Copied @ %s \n" "$(date +%H.%M.%S)"  ; fi
	fi
	
	sleep 1
	
	((Counter+=1)) ;  [[ $Counter -ge 4 ]] && Counter=0 ; UpdSets= ; CopyFail=
		
done

