#!/usr/bin/env bash

##  qqX - quickemu quickget X terminal project

#   Helper file for qqX settings file updates

##  Copyright (c)  Alex Genovese   https://github.com/qqxproject
#   SMALL CODE SNIPPETS eg the function printColor MAY BE USED
#   PERMISSIVELY in projects as MIT or similar, providing CLEAR ATTRIBUTIONS are shown.

# 	Otherwise:

# Licence  GPL3   https://www.gnu.org/licenses

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# https://www.gnu.org/licenses

# IF CODE IN GENERAL BECOMES USED IN ANY OTHER PROJECT,
# THE GPL3 LICENCE APPLIES & YOU SHOULD SHOW CLEAR ATTRIBUTIONS.


##  Older code from 'ffX project' (c)  Alex Genovese  Refactored @ 03/2024


printf "\033c"
printColor "\n\n  To create shortcut launchers, the name of a Linux Terminal Emulator is needed \n\n"

# 'UserTerm' may be supplied by a calling script or setup installer settings

if [[ ! $UserTerm ]]; then

  echo "  Checking ...."; echo

  ## Almost all terminal emulators have 'term' as part of the name.
  #  Check here for the notable exception:
  UserTerm="$(pgrep -li  "konsole" )"

  TermWordChk="$(pgrep -a term | grep qqX | awk '{print $2}')"
  if [[ $TermWordChk ]]; then
    printf "\n  Terminal might be \'%s\' \n\n" "$(basename "$TermWordChk")"
    [[ ! $UserTerm ]] && UserTerm="$(basename "$TermWordChk")"
  else
    printf "\n  Terminal might be: \n\n"
    pgrep -a term
    printf "\n\n"
  fi

  if [[ $UserTerm ]]; then
    printColor "\n\n  UserTerm is %s ? " "$UserTerm"
    printf "\n\n  Is this correct?  [enter] yes  [n] no, possibly not \n\n"
    read -rp "   >  "   FirstTermChk
    echo
    if [[ $FirstTermChk == "n" ]]; then UserTerm=; else UserTerm_Found=1; fi
  fi

fi

if [[ $WSL_Install ]]; then

  # add basic suggestion
  [[ $(type -p "gnome-terminal") ]] && UserTerm="gnome-terminal"

elif [[ ! $UserTerm ]]; then

  echo "  Checking ...."; echo
  # Scan for processes with 'term' as part of the name  (& ignore lines with scriptname )
  # https://stackoverflow.com/questions/35006457/choosing-between-0-and-bash-source & http://mywiki.wooledge.org/BashFAQ/001

  TermGrep=()

  while IFS= read -r Line; do
    [[ "$Line" == *"qqX_termfind"* ]] && continue
    TermGrep+=("$Line")
  done  <  <(pgrep -li "term")

  TermCount="${#TermGrep[*]}"

  if [[ "$TermCount" -eq 1 ]]; then

    UserTerm_PID="${TermGrep[0]}"
    UserTerm_PID="$(echo "$UserTerm_PID" | tr -cd '[:digit:]')"

  elif [[ "$TermCount" -gt 1 ]]; then

    printf "\n  %s\n\n" "${TermGrep[@]}"
    printf "  Some lightweight terminals may not be compatible (See 'known-issues')"
    if [[ $UserTerm == "gnome-terminal" ]]; then
      printf "\n\n  'gnome-terminal' is also used by various desktops, such as Mint Cinnamon, Budgie and Ubuntu ..."
        if ! gnome-terminal --help-window-options 2>/dev/null | grep -qs geometry ; then
        printf "\n\n   However some distros are aliasing 'gnome-terminal' as a call to kgx / gnome console"
        printf "\n\n   CAUTION:  either select 'kgx' or install the non-aliased version ...."
          UserTerm="kgx"
        fi
    fi
    printf "\n\n  Checking the menubar for help > about, could show the name ...."
    printf "\n\n  Enter the number of your Terminal Emulator,  or  [n] none of these, do more tests \n\n"
    read -rp "  >  "  UserTerm_PID
    echo
    if [[ $UserTerm_PID == "n" ]]; then UserTerm_PID= ; UserTerm_Found= ; fi

  fi

  if [[ $UserTerm_PID ]]; then

    if [[ -d "/proc/$UserTerm_PID" ]]; then
      UserTerm="$(realpath /proc/"$UserTerm_PID"/exe)"
      UserTerm="${UserTerm##*/}"
    else
      echo "  Error:  PID not found"; echo
      UserTerm= ; UserTerm_PID= ; UserTerm_Found=
     fi
  fi

  if [[ $UserTerm ]] && [[ ! $(type -p "$UserTerm") ]]; then UserTerm=
  fi

  if [[ ! $UserTerm ]]; then
    TermWordChk="$(pgrep -a term | grep qqX | awk '{print $2}')"
    if [[ $TermWordChk ]]; then  UserTerm="$TermWordChk" ;  UserTerm_Found=
    fi
  fi

fi

while [[ ! $UserTerm_Found ]]; do

  if [[ ! $UserTerm ]]; then

    if [[ ! $WSL_Install ]]; then

      PID_Term_ProbeArr=()
      echo
      echColor "  Basic tests are unable to find name of your terminal emulator"; echo

      # LOAD NOTES from function at start of calling script qqX installer
      print_terminal_notes
      echo
      echo "  Further tests: "

      if [[ $TermFind_ReRun ]]; then
        echo; echo
        echo "  SHELL is $SHELL" ; echo
        head "/proc/$PPID/status"
        echo
      fi

      UserTerm="$(realpath /proc/$PPID/exe)"
      UserTerm="${UserTerm##*/}"
      PID_Term_ProbeArr+=("$UserTerm")

      if [[ $TermFind_ReRun ]]; then
        echo "  UserTerm is $UserTerm" ; echo
        echo "  Parent PID is $PPID" ; echo
        echo "  Process Command is $(cat "/proc/$PPID/comm" 2>/dev/null)"; echo
        echo
      fi

      while [[ "${GrandParentPID:-$PPID}" -gt 1 ]]; do

        GrandParentPID="$(grep -i -e "PPid:" "/proc/${GrandParentPID:-$PPID}/status")"
        GrandParentPID="$(echo "$GrandParentPID" | tr -cd '[:digit:]')"
        #  See  http://mywiki.wooledge.org/BashFAQ/073

        [[ $TermFind_ReRun ]] && echo "  *******************************" && echo

        if [[ "$GrandParentPID" -gt 1 ]]; then

          if [[ $TermFind_ReRun ]]; then
            echo
            head "/proc/$GrandParentPID/status"
            echo
            echo "  GrandParentPID is $GrandParentPID"; echo
            echo "  Process Command is $(cat "/proc/$GrandParentPID/comm" 2>/dev/null)"; echo
          fi

          GrandParent_Name="$(realpath /proc/"$GrandParentPID"/exe)"
          GrandParent_Name="${GrandParent_Name##*/}"
          UserTerm="$GrandParent_Name"
          PID_Term_ProbeArr+=("$UserTerm")
          [[ $TermFind_ReRun ]] && echo "  GrandParent_Name is $GrandParent_Name"; echo

        fi

      done

      TermWordChk="$(pgrep -a term | grep qqX | awk '{print $2}')"
      if [[ $TermWordChk ]]; then  printf "\n  Terminal might also be \'%s\' \n" "$(basename "$TermWordChk")"
      fi

    fi

    if [[ $TermFind_ReRun || $WSL_Install ]]; then

      if [[ $ErrorPID ]] && [[ ! $WSL_Install ]]; then  echo "  PID not found ...." ; echo ; ErrorPID=
      fi

      echo
      echo "  To create a shortcut, a name is needed ....   Check/Recheck the script output"; echo
      echo "  You can enter the name here, if you know the correct command name"; echo
      echo "  Checking the menubar for help > about, could show the name ...."; echo
      echo "  Or use a different method & manually add 'UserTerm' "; echo
      echo "  to the 'setup and install' script, at the start."; echo; echo

      [[ $WSL_Install ]] && echColor "  You may need to install a terminal, if you have not done so. "; echo

      echColor "  Enter the PID number of your Terminal Emulator, [n] if you know the name, [q] to quit "; echo
      read -rp "  >  "  UserTerm_PID
      echo

      ProbTerm=" Possibly"

      if [[ $UserTerm_PID == "q" ]]; then  exit

      elif [[ $UserTerm_PID == "n" ]]; then

        # Unlikely but with so many Linux distro & desktop combinations and customisations ...
        read -rp "  Command Name for you terminal is:  "  UserTerm
        UserTerm_Found=1
        ProbTerm=
        echo

      else

        if [[ -d "/proc/$UserTerm_PID" ]]; then
          UserTerm="$(realpath /proc/"$UserTerm_PID"/exe 2>/dev/null)"
          UserTerm="${UserTerm##*/}"
        else
          UserTerm=
          UserTerm_PID=
          UserTerm_Found=
          ErrorPID=1
        fi

      fi

    else

      echo
      i=0
      for  ProcessName in "${PID_Term_ProbeArr[@]}" ; do
        [[ $ProcessName == "bash" ]] || [[ $ProcessName == "dash" ]] || [[ $ProcessName == "sh" ]] && ProcessShellpoint="$i"  &&  ((ProcessShellpoint+=1))
        ((i+=1))
      done

      if [[ $ProcessShellpoint ]]; then  UserTerm="${PID_Term_ProbeArr[$ProcessShellpoint]}"; else  UserTerm="${PID_Term_ProbeArr[0]}"; fi
      # Usually either the first one or the one after the first occurance of 'sh'
      ProbTerm=" Probably"

    fi

    TermFind_ReRun=1
    GrandParentPID=

  fi

  # Add any modifiers here, if needed
  if [[ "$UserTerm" == gnome-terminal* ]]; then
    UserTerm="gnome-terminal"
    if ! gnome-terminal --help-window-options 2>/dev/null | grep -qs geometry ; then
        printf "\n\n   However some distros are aliasing 'gnome-terminal' as a call to kgx / gnome console"
        printf "\n\n   CAUTION:  either select 'kgx' or install the non-aliased version ...."
      UserTerm="kgx"
    fi
  fi

  if [[ $UserTerm ]] ; then
    echColor " $ProbTerm UserTerm is $UserTerm" ; echo
    [[ $UserTerm == "gnome-terminal" ]] && echo "  Note: 'gnome-terminal' is also used by various desktops, such as Mint Cinnamon, Budgie and Ubuntu ..." && echo
    echo "  Is this correct?  [enter] yes, probably ...   [n] no, I am still not sure " ; echo
    read -rp "  >  "
    echo
    if [[ $REPLY == "n" ]]; then UserTerm= ; UserTerm_Found= ; else  UserTerm_Found=1 ; fi
  fi

  if [[ ! $UserTerm ]]; then printf "\033c"; echo; echo ; fi
  ProbTerm=

done


# LOAD NOTES from function at start of calling script qqX installer

print_terminal_notes

echo
echo; echColor "  Terminal = $UserTerm"; echo
read -rp "  [enter] to continue > "
echo

# https://code.visualstudio.com/  (recommended)
# vim:tabstop=2:shiftwidth=2:expandtab
